function gera_afterload(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 15-Apr-2021 18:12:45

% Create figure
figure1 = figure('PaperOrientation','landscape','PaperType','A5',...
    'PaperSize',[8.2639 5.8472]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','R_s = 1.0','LineWidth',2.5);

% Create plot
plot(X2,Y2,'DisplayName','R_s = 0.75','LineWidth',2.5);

% Create plot
plot(X3,Y3,'DisplayName','R_s = 0.5','LineWidth',2.5);

% Create plot
plot1 = plot(X4,Y4,'DisplayName','Fechamento da Válvula Aórtica',...
    'Marker','o',...
    'LineWidth',2.5,...
    'LineStyle','none',...
    'Color',[0.466666666666667 0.466666666666667 0.466666666666667]);

% Create text
text('Parent',axes1,'Units','normalized','VerticalAlignment','top',...
    'String',{'','Linear:  y = 2.466*x - 62.8'},...
    'Position',[0.05 0.95 0]);

% Get xdata from plot
xdata1 = get(plot1, 'xdata');
% Get ydata from plot
ydata1 = get(plot1, 'ydata');
% Make sure data are column vectors
xdata1 = xdata1(:);
ydata1 = ydata1(:);


% Remove NaN values and warn
nanMask1 = isnan(xdata1(:)) | isnan(ydata1(:));
if any(nanMask1)
    warning('GeneratedCode:IgnoringNaNs', ...
        'Data points with NaN coordinates will be ignored.');
    xdata1(nanMask1) = [];
    ydata1(nanMask1) = [];
end

% Find x values for plotting the fit based on xlim
axesLimits1 = xlim(axes1);
xplot1 = linspace(axesLimits1(1), axesLimits1(2));

% Preallocate for "Show equations" coefficients
coeffs1 = cell(1,1);

% Find coefficients for polynomial (order = 1)
fitResults1 = polyfit(xdata1,ydata1,1);
% Evaluate polynomial
yplot1 = polyval(fitResults1,xplot1);

% Save type of fit for "Show equations"
fittypesArray1(1) = 2;

% Save coefficients for "Show Equation"
coeffs1{1} = fitResults1;

% Plot the fit
fitLine1 = plot(xplot1,yplot1,'DisplayName','   linear','Tag','linear',...
    'Parent',axes1,...
    'LineWidth',2.5);

% Set new line in proper position
setLineOrder(axes1,fitLine1,plot1);

% "Show equations" was selected
showEquations(fittypesArray1,coeffs1,4,axes1);

% Create ylabel
ylabel('Pve (mmHg)','FontName','Times New Roman');

% Create xlabel
xlabel('Vve (ml)','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 110]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 120]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.1838706907156 0.71277409817596 0.270454539121552 0.159771750129749],...
    'FontSize',11);

%-------------------------------------------------------------------------%
function setLineOrder(axesh1, newLine1, associatedLine1)
%SETLINEORDER(AXESH1,NEWLINE1,ASSOCIATEDLINE1)
%  Set line order
%  AXESH1:  axes
%  NEWLINE1:  new line
%  ASSOCIATEDLINE1:  associated line

% Get the axes children
hChildren = get(axesh1,'Children');
% Remove the new line
hChildren(hChildren==newLine1) = [];
% Get the index to the associatedLine
lineIndex = find(hChildren==associatedLine1);
% Reorder lines so the new line appears with associated data
hNewChildren = [hChildren(1:lineIndex-1);newLine1;hChildren(lineIndex:end)];
% Set the children:
set(axesh1,'Children',hNewChildren);

%-------------------------------------------------------------------------%
function showEquations(fittypes1, coeffs1, digits1, axesh1)
%SHOWEQUATIONS(FITTYPES1,COEFFS1,DIGITS1,AXESH1)
%  Show equations
%  FITTYPES1:  types of fits
%  COEFFS1:  coefficients
%  DIGITS1:  number of significant digits
%  AXESH1:  axes

n = length(fittypes1);
txt = cell(length(n + 1) ,1);
txt{1,:} = ' ';
for i = 1:n
    txt{i + 1,:} = getEquationString(fittypes1(i),coeffs1{i},digits1,axesh1);
end
text(.05,.95,txt,'parent',axesh1, ...
    'verticalalignment','top','units','normalized');

%-------------------------------------------------------------------------%
function [s1, a1] = getEquationString(fittype1, coeffs1, digits1, axesh1)
%GETEQUATIONSTRING(FITTYPE1,COEFFS1,DIGITS1,AXESH1)
%  Get "Show Equation" text
%  FITTYPE1:  type of fit
%  COEFFS1:  coefficients
%  DIGITS1:  number of significant digits
%  AXESH1:  axes

if isequal(fittype1, 0)
    s1 = 'Cubic spline interpolant';
elseif isequal(fittype1, 1)
    s1 = 'Shape-preserving interpolant';
else
    if isequal(fittype1, 2)
        a1 = 'Linear: ';
    elseif isequal(fittype1, 3)
        a1 = 'Quadratic: ';
    elseif isequal(fittype1, 4)
        a1 = 'Cubic: ';
    elseif isequal(fittype1, 5)
        a1 = '4th degree: ';
    elseif isequal(fittype1, 6)
        a1 = '5th degree: ';
    elseif isequal(fittype1, 7)
        a1 = '6th degree: ';
    elseif isequal(fittype1, 8)
        a1 = '7th degree: ';
    elseif isequal(fittype1, 9)
        a1 = '8th degree: ';
    elseif isequal(fittype1, 10)
        a1 = '9th degree: ';
    elseif isequal(fittype1, 11)
        a1 = '10th degree: ';
    end
    op = '+-';
    format1 = ['%s %0.',num2str(digits1),'g*x^{%s} %s'];
    format2 = ['%s %0.',num2str(digits1),'g'];
    xl = get(axesh1, 'xlim');
    fit =  fittype1 - 1;
    s1 = sprintf('%s y =',a1);
    th = text(xl*[.95;.05],1,s1,'parent',axesh1, 'vis','off');
    if abs(coeffs1(1) < 0)
        s1 = [s1 ' -'];
    end
    for i = 1:fit
        sl = length(s1);
        if ~isequal(coeffs1(i),0) % if exactly zero, skip it
            s1 = sprintf(format1,s1,abs(coeffs1(i)),num2str(fit+1-i), op((coeffs1(i+1)<0)+1));
        end
        if (i==fit) && ~isequal(coeffs1(i),0)
            s1(end-5:end-2) = []; % change x^1 to x.
        end
        set(th,'string',s1);
        et = get(th,'extent');
        if et(1)+et(3) > xl(2)
            s1 = [s1(1:sl) sprintf('\n     ') s1(sl+1:end)];
        end
    end
    if ~isequal(coeffs1(fit+1),0)
        sl = length(s1);
        s1 = sprintf(format2,s1,abs(coeffs1(fit+1)));
        set(th,'string',s1);
        et = get(th,'extent');
        if et(1)+et(3) > xl(2)
            s1 = [s1(1:sl) sprintf('\n     ') s1(sl+1:end)];
        end
    end
    delete(th);
    % Delete last "+"
    if isequal(s1(end),'+')
        s1(end-1:end) = []; % There is always a space before the +.
    end
    if length(s1) == 3
        s1 = sprintf(format2,s1,0);
    end
end

